/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./src/components/icons/sidebarIcons/RecruitmentIcon copy 2.vue')['default']
    3: typeof import('./src/components/icons/sidebarIcons/RecruitmentIcon copy 3.vue')['default']
    4: typeof import('./src/components/icons/sidebarIcons/RecruitmentIcon copy 4.vue')['default']
    copy: typeof import('./src/components/icons/sidebarIcons/RecruitmentIcon copy.vue')['default']
    DashboardIcon: typeof import('./src/components/icons/sidebarIcons/DashboardIcon.vue')['default']
    DepartmentIcon: typeof import('./src/components/icons/sidebarIcons/DepartmentIcon.vue')['default']
    EmployeeIcon: typeof import('./src/components/icons/sidebarIcons/EmployeeIcon.vue')['default']
    NavbarItem: typeof import('./src/components/NavbarItem.vue')['default']
    RecruitmentIcon: typeof import('./src/components/icons/sidebarIcons/RecruitmentIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleIcon: typeof import('./src/components/icons/sidebarIcons/ScheduleIcon.vue')['default']
    SettingsIcon: typeof import('./src/components/icons/sidebarIcons/SettingsIcon.vue')['default']
    SidebarItem: typeof import('./src/components/SidebarItem.vue')['default']
    SupportIcon: typeof import('./src/components/icons/sidebarIcons/SupportIcon.vue')['default']
  }
}
